# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c23d3e87f7f3894780ac3590012e490225baf7ca644fca0152eca97046da59bb291ca2aca23c9d7ab3437e316e7abab8d072e32bb29bf7e357d0472a12911c6

test:
  secret_key_base: d6e15366724edf75489586d18d219f03a335c8747006cc6ebcd2a59dfa533e9a4d71c7e4fa0ce1d134d50ff0779a0eef18343bd15193b96022a6afbb81132bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
